# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LoopdSDK_Demo' do
pod 'LoopdSDK'
end

target 'LoopdSDK_DemoTests' do

end

target 'LoopdSDK_DemoUITests' do

end

