source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LoopdSDK_Example', :exclusive => true do
  pod "LoopdSDK", :path => "../"
end

target 'LoopdSDK_Tests', :exclusive => true do
  pod "LoopdSDK", :path => "../"

  
end
